kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-k8s
  labels:
    podindex: "0"
    app: prometheus-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"

