kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: sample-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: php-apache
    #apiVersion: extensions/v1beta1
    #kind: Deployment
    #name: sample-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Pods
    pods:
      #metricName: http_requests
      metricName: memory_rss
      targetAverageValue: 500m

