apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: custom-metrics
  namespace: kube-system
  labels:
    app: custom-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-metrics
  template:
    metadata:
      labels:
        app: custom-metrics
    spec:
      containers:
      - name: custom-metrics
        image: qaregistry.yatra.com/k8s-prometheus-adapter-amd64
        args:
        - --prometheus-url=http://prometheus-k8s.default:9090
        - --metrics-relist-interval=30s
        - --rate-interval=60s
        - --v=4
        - --logtostderr=true
        ports:
        - containerPort: 443
        securityContext:
          runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: kube-system
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: custom-metrics
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
spec:
  insecureSkipTLSVerify: true
  group: custom.metrics.k8s.io
  groupPriorityMinimum: 1000
  versionPriority: 5
  service:
    name: api
    namespace: kube-system
  version: v1beta1
