apiVersion: v1
kind: Service
metadata:
  labels:
    app: fresco
    k8s-app: fresco
  name: fresco
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: jmx
    port: 5556
    targetPort: 5556
  selector:
    app: fresco
  type: LoadBalancer

