apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: monitoring
data:
  config.yml: |-
    global:
      smtp_smarthost: 'smtp1.yatra.in:25'
      smtp_from: 'linuxadmin@yatra.com'
      #smtp_auth_username: 'your_smtp_user'
      #smtp_auth_password: 'your_smtp_pass'
    templates:
    - '/etc/alertmanager/template/*.tmpl'
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 30m
      receiver: default-receiver
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      # Apply inhibition if the alertname is the same.
      equal: ['alertname', 'cluster', 'service']
    receivers:
    - name: 'default-receiver'
      email_configs:
      - to: 'pawan.kumar1@yatra.com'
        send_resolved: true
        require_tls: false
