apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - my-asn: 64522
      peer-asn: 64512
      peer-address: 192.168.50.52
    address-pools:
    - name: my-ip-space
      avoid-buggy-ips: true
      cidr:
      - 10.100.1.1/24
      advertisements:
      - localpref: 100
